package View;

import Controller.MainController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Felix on 15.10.2016.
 */
public class MainView extends JFrame {
    private MainController controller;
    private JTextArea moderator;
    private JTextArea questionArea;
    private JButton play;
    private JButton answerD;
    private JButton answerC;
    private JButton answerB;
    private JButton answerA;
    private JLabel playerName;
    private JLabel playerLevel;
    private JPanel contentPanel;

    public MainView(MainController controller) {
        this.controller = controller;

        this.$$$setupUI$$$();
        this.setContentPane(contentPanel);
        this.pack();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);

        playerName.setText("Name:");
        playerLevel.setText("Level:");

        answerA.setEnabled(false);
        answerB.setEnabled(false);
        answerC.setEnabled(false);
        answerD.setEnabled(false);


        play.addActionListener((e) -> {
            play();
            //JOptionPane.showInputDialog("Wie heißen Sie?");
            play.setEnabled(false);
            answerA.setEnabled(true);
            answerB.setEnabled(true);
            answerC.setEnabled(true);
            answerD.setEnabled(true);
            updateQuestionAndAnswer();

        });
        answerA.addActionListener((e) -> {
            handleAnswer("A");
        });
        answerB.addActionListener((e) -> {
            handleAnswer("B");
        });
        answerC.addActionListener((e) -> {
            handleAnswer("C");
        });
        answerD.addActionListener((e) -> {
            handleAnswer("D");
        });

    }

    public void play() {
        this.controller.createPlayer("Ulf");
    }

    public void updateQuestionAndAnswer() {
        this.playerName.setText("Name:" + this.controller.getPlayerName());
        this.playerLevel.setText("Level:" + this.controller.getPlayerLevel());
        this.moderator.setText("Bitte eine Antwort auswählen!");
        String[] z = this.controller.getQuestionAndAnswers();
        this.questionArea.setText(z[0]);
        this.answerA.setText("A:" + z[0]);
        this.answerB.setText("B:" + z[1]);
        this.answerC.setText("C:" + z[2]);
        this.answerD.setText("D:" + z[3]);

    }


    public void handleAnswer(String answer) {
        if (controller.answer(answer) == true) {
            this.updateQuestionAndAnswer();
        } else {
            contentPanel.setEnabled(false);
            moderator.setText("Leider falsch...Viel Glück beim nächsten Mal!");
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        moderator = new JTextArea();
        contentPanel.add(moderator, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        questionArea = new JTextArea();
        contentPanel.add(questionArea, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        play = new JButton();
        play.setText("Play!");
        contentPanel.add(play, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        answerD = new JButton();
        answerD.setText("Button");
        contentPanel.add(answerD, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        answerC = new JButton();
        answerC.setText("Button");
        contentPanel.add(answerC, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        answerB = new JButton();
        answerB.setText("Button");
        contentPanel.add(answerB, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        answerA = new JButton();
        answerA.setText("Button");
        contentPanel.add(answerA, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        playerName = new JLabel();
        playerName.setText("Label");
        contentPanel.add(playerName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        playerLevel = new JLabel();
        playerLevel.setText("Label");
        contentPanel.add(playerLevel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
